import React from "react";
import { useNavigate } from "react-router-dom";
import "./Landing.css";

const featureImages = [
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80", // Personalized
  "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80", // AI-Powered
  "https://images.unsplash.com/photo-1510626176961-4b57d4fbad04?auto=format&fit=crop&w=400&q=80", // Health & Safety
  "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80"  // Easy to Use
];

const Landing = () => {
  const navigate = useNavigate();

  return (
    <div className="landing-container">
      <header className="landing-header fade-in">
        <h1>Medimeal</h1>
        <p>Your Health, Your Meal – Powered by AI</p>
      </header>
      <section className="landing-hero slide-up">
        <div className="hero-content">
          <div className="hero-text">
            <h2>Personalized Food Recommendations for Your Health</h2>
            <p>
              Medimeal uses advanced AI to recommend meal plans tailored to your medication, age, and health conditions. Eat smarter, feel better, and take control of your wellness journey.
            </p>
            <div className="landing-cta">
              {/* AI Food Recommendation button removed */}
            </div>
          </div>
          <img className="hero-img fade-in" src="https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=500&q=80" alt="Healthy food" />
        </div>
      </section>
      <section className="landing-features fade-in">
        <div>
          <img src={featureImages[0]} alt="Personalized" className="feature-img" />
          <h3>Personalized</h3>
          <p>Get meal plans that fit your unique health profile, including medication, age, and conditions.</p>
        </div>
        <div>
          <img src={featureImages[1]} alt="AI-Powered" className="feature-img" />
          <h3>AI-Powered</h3>
          <p>Recommendations generated by advanced AI for safe, science-backed suggestions.</p>
        </div>
        <div>
          <img src={featureImages[2]} alt="Health & Safety" className="feature-img" />
          <h3>Health & Safety</h3>
          <p>Designed to support your medication and health needs, prioritizing your well-being.</p>
        </div>
        <div>
          <img src={featureImages[3]} alt="Easy to Use" className="feature-img" />
          <h3>Easy to Use</h3>
          <p>Simple login and signup, intuitive interface, and instant access to your meal plans.</p>
        </div>
      </section>
      <section className="landing-howitworks slide-up">
        <h2>How It Works</h2>
        <div className="howitworks-steps">
          <div>
            <span className="howitworks-stepnum">1</span>
            <h4>Sign Up & Enter Details</h4>
            <p>Create your account and provide your age, medication, and health conditions.</p>
          </div>
          <div>
            <span className="howitworks-stepnum">2</span>
            <h4>Get Personalized Meal Plans</h4>
            <p>Receive AI-powered food recommendations tailored just for you.</p>
          </div>
          <div>
            <span className="howitworks-stepnum">3</span>
            <h4>Eat Healthy, Stay Happy</h4>
            <p>Follow your meal plan and enjoy a healthier lifestyle with Medimeal.</p>
          </div>
        </div>
      </section>
      <section className="landing-testimonials fade-in">
        <h2>What Our Users Say</h2>
        <div className="testimonials-list">
          <div>
            <p>"Medimeal made it so easy to eat right for my health! The AI suggestions are spot on."</p>
            <span>- Priya, 34</span>
          </div>
          <div>
            <p>"I love how it considers my medication and conditions. Highly recommended!"</p>
            <span>- Rahul, 52</span>
          </div>
          <div>
            <p>"Simple, fast, and effective. My energy levels have improved!"</p>
            <span>- Anjali, 28</span>
          </div>
        </div>
      </section>
      <section className="landing-finalcta slide-up">
        <h2>Ready to get your personalized meal plan?</h2>
        <button
          onClick={() => {
            const user = JSON.parse(localStorage.getItem('medimeal_user'));
            if (user && user.email) {
              navigate('/recommend');
            } else {
              navigate('/login');
            }
          }}
        >
          Get Started
        </button>
      </section>
      <section className="landing-pricing fade-in">
        <h2 style={{ textAlign: 'center', color: '#22c55e', marginBottom: '1.5rem' }}>Choose Your Plan</h2>
        <div className="pricing-cards">
          <div className="pricing-card normal">
            <h3>Normal</h3>
            <ul>
              <li>Personalized food recommendations</li>
              <li>Rule-based engine</li>
              <li>Basic AI Q&A</li>
              <li>Access to meal timeline</li>
            </ul>
            <div className="pricing-price">Free</div>
            <button className="pricing-btn" onClick={() => navigate('/signup')}>Start Free</button>
          </div>
          <div className="pricing-card premium best-value">
            <h3>Premium</h3>
            <ul>
              <li>All Normal features</li>
              <li>Advanced AI assistant</li>
              <li>Priority support</li>
              <li>Alternative food suggestions</li>
              <li>Upload medical reports</li>
              <li>Unlimited recommendations</li>
              <li>Personal dietitian Q&A</li>
              <li>Early access to new features</li>
            </ul>
            <div className="pricing-price">₹199/mo <span style={{ color: '#64748b', fontSize: '0.95rem' }}>(or $2.49/mo)</span></div>
            <button className="pricing-btn premium">Go Premium</button>
          </div>
        </div>
      </section>
      <footer className="landing-footer">
        &copy; {new Date().getFullYear()} Medimeal. All rights reserved.
      </footer>
    </div>
  );
};

export default Landing;