import React from "react";
import { useNavigate } from "react-router-dom";
import "./Landing.css";

const featureImages = [
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80", // Personalized
  "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=800&q=80", // Healthy & Tasty
  "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80", // AI-Powered
  "https://images.unsplash.com/photo-1510626176961-4b57d4fbad04?auto=format&fit=crop&w=400&q=80", // Health & Safety
  "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"  // Easy to Use
];

const Landing = () => {
  const navigate = useNavigate();

  return (
    <>
      <header
        className="landing-header fade-in w-full"
        style={{
          background: '#1a237e',
          width: '100%',
          boxShadow: '0 2px 8px rgba(26,35,126,0.08)',
          paddingTop: '2rem',
          paddingBottom: '2rem'
        }}
      >
        <h1
          style={{
            fontWeight: 700,
            fontSize: '3rem',
            letterSpacing: '2px',
            margin: 0,
            color: '#fff',
            whiteSpace: 'nowrap',
            textAlign: 'center'
          }}
        >
          Medimeal
        </h1>
        <p
          style={{
            fontSize: '1.3rem',
            fontWeight: 400,
            marginTop: '0.5rem',
            color: '#fff',
            textAlign: 'center'
          }}
        >
          Your Health, Your Meal – Powered by AI
        </p>
      </header>
      <div className="landing-container min-h-screen w-full text-gray-900" style={{ background: "#e3f2fd url('https://www.shutterstock.com/image-photo/food-products-recommended-osteoporosis-healthy-260nw-2596052607.jpg') center/cover no-repeat", position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', inset: 0, background: '#e3f2fd', opacity: 0.7, zIndex: 0 }} />
        <div style={{ position: 'absolute', inset: 0, background: '#f4f7fa', opacity: 0.5, zIndex: 1 }} />
        <div style={{ position: 'relative', zIndex: 2 }}>
          {/* HERO SECTION */}
          <section className="landing-hero slide-up w-full">
            <div className="hero-content w-full px-8 flex flex-wrap items-start justify-start gap-10">
              <div className="hero-text">
                <h2 style={{ fontSize: '2.3rem', color: 'var(--primary-main)', fontWeight: 600, marginBottom: '1.2rem' }}>Personalized Food Recommendations for Your Health</h2>
                <p style={{ fontSize: '1.15rem', color: 'var(--secondary)', marginBottom: '2.2rem', maxWidth: 600 }}>Medimeal uses advanced AI to recommend meal plans tailored to your medication, age, and health conditions. Eat smarter, feel better, and take control of your wellness journey.</p>
                <button className="landing-cta" style={{ padding: '1rem 2.5rem', fontSize: '1.15rem', borderRadius: 30, background: '#1a237e', color: '#fff', fontWeight: 600, border: 'none', boxShadow: '0 0 12px #1a237e', marginTop: 10 }} onClick={() => navigate('/signup')}>Get Started</button>
              </div>
              <img className="hero-img fade-in" src="https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80" alt="Healthy food" />
            </div>
          </section>

          {/* FEATURES SECTION */}
          <section className="landing-features fade-in w-full px-8 flex flex-wrap justify-start gap-8" style={{ marginTop: 40, background: '#e3f2fd' }}>
            {[
              { img: featureImages[0], title: 'Personalized', desc: 'Get meal plans that fit your unique health profile, including medication, age, and conditions.' },
              { img: featureImages[1], title: 'Healthy & Tasty', desc: 'Enjoy delicious, nutritious meals that are as good for your taste buds as they are for your health.' },
              { img: featureImages[2], title: 'AI-Powered', desc: 'Recommendations generated by advanced AI for safe, science-backed suggestions.' },
              { img: featureImages[3], title: 'Health & Safety', desc: 'Designed to support your medication and health needs, prioritizing your well-being.' },
              { img: featureImages[4], title: 'Easy to Use', desc: 'Simple login and signup, intuitive interface, and instant access to your meal plans.' }
            ].map((f, i) => (
              <div key={f.title} className="feature-card" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', background: '#fff', borderRadius: 18, boxShadow: '0 2px 12px rgba(52,211,153,0.10)', padding: '1.5rem 1.2rem 1.2rem 1.2rem', minWidth: 220, maxWidth: 260, textAlign: 'center', borderTop: '4px solid var(--primary-main)', margin: '0 0.5rem 1.5rem 0.5rem' }}>
                <img src={f.img} alt={f.title} className="feature-img" />
                <h3 style={{ color: '#1a237e', marginBottom: 8, marginTop: 10 }}>{f.title}</h3>
                <p style={{ color: '#334155', fontSize: '1.05rem' }}>{f.desc}</p>
              </div>
            ))}
          </section>

          {/* HOW IT WORKS SECTION */}
          <section className="landing-howitworks slide-up w-full px-8" style={{ marginTop: 30 }}>
            <h2 style={{ color: '#1a237e', marginBottom: 24 }}>How It Works</h2>
            <div className="howitworks-steps w-full flex flex-wrap justify-start gap-8">
              {[
                { step: 1, title: 'Sign Up & Enter Details', desc: 'Create your account and provide your age, medication, and health conditions.' },
                { step: 2, title: 'Get Personalized Meal Plans', desc: 'Receive AI-powered food recommendations tailored just for you.' },
                { step: 3, title: 'Eat Healthy, Stay Happy', desc: 'Follow your meal plan and enjoy a healthier lifestyle with Medimeal.' }
              ].map((s, i) => (
                <div key={s.step} className="howitworks-card" style={{ background: '#fff', borderRadius: 12, boxShadow: '0 2px 8px rgba(34,197,94,0.08)', padding: '1.5rem', minWidth: 200, maxWidth: 300, flex: '1 1 200px', marginBottom: 16, borderTop: '4px solid var(--primary-main)', position: 'relative' }}>
                  <span className="howitworks-stepnum" style={{ background: 'var(--accent)', color: '#fff', border: '2px solid var(--primary-main)', marginBottom: 8 }}>{s.step}</span>
                  <h4 style={{ margin: '0.7rem 0 0.3rem 0', color: '#1a237e', fontWeight: 600 }}>{s.title}</h4>
                  <p style={{ color: 'var(--secondary)', fontSize: '1.05rem' }}>{s.desc}</p>
                </div>
              ))}
            </div>
          </section>

          {/* TESTIMONIALS SECTION */}
          <section className="landing-testimonials fade-in w-full px-8" style={{ marginTop: 30 }}>
            <h2 style={{ color: '#1a237e', marginBottom: 24 }}>What Our Users Say</h2>
            <div className="testimonials-list w-full flex flex-wrap justify-start gap-8">
              {[
                { quote: '"Medimeal made it so easy to eat right for my health! The AI suggestions are spot on."', name: 'Priya, 34' },
                { quote: '"I love how it considers my medication and conditions. Highly recommended!"', name: 'Rahul, 52' },
                { quote: '"Simple, fast, and effective. My energy levels have improved!"', name: 'Anjali, 28' }
              ].map((t, i) => (
                <div key={t.name} className="testimonial-card" style={{ background: '#1a237e', borderRadius: 12, boxShadow: '0 2px 8px rgba(34,197,94,0.08)', padding: '1.5rem', minWidth: 220, maxWidth: 300, flex: '1 1 220px', marginBottom: 16, fontStyle: 'italic', color: '#fff', borderLeft: '4px solid var(--primary-main)' }}>
                  <p style={{ marginBottom: 8 }}>{t.quote}</p>
                  <span style={{ display: 'block', marginTop: 8, fontSize: '0.95rem', color: '#fff', fontWeight: 700, fontStyle: 'normal' }}>{t.name}</span>
                </div>
              ))}
            </div>
          </section>

          {/* FINAL CTA SECTION */}
          <section className="landing-finalcta slide-up" style={{ marginTop: 40 }}>
            <h2 style={{ color: 'var(--primary-main)', marginBottom: 18 }}>Ready to get your personalized meal plan?</h2>
            <button
              style={{ padding: '1rem 2.5rem', fontSize: '1.15rem', borderRadius: 30, background: '#1a237e', color: '#fff', fontWeight: 600, border: 'none', boxShadow: '0 0 12px #1a237e' }}
              onClick={() => {
                const user = JSON.parse(localStorage.getItem('medimeal_user'));
                if (user && user.email) {
                  navigate('/recommend');
                } else {
                  navigate('/login');
                }
              }}
            >
              Get Started
            </button>
          </section>

          {/* PRICING SECTION */}
          <section className="landing-pricing fade-in w-full px-8" style={{ marginTop: 40 }}>
            <h2 style={{ textAlign: 'center', color: '#1a237e', marginBottom: '1.5rem' }}>Choose Your Plan</h2>
            <div className="pricing-cards w-full flex flex-wrap justify-start gap-8">
              <div className="pricing-card normal">
                <h3 style={{ color: '#1a237e' }}><span role="img" aria-label="normal">⭐</span> Normal</h3>
                <ul style={{ fontSize: '1.15rem' }}>
                  <li>Personalized food recommendations</li>
                  <li>Rule-based engine</li>
                  <li>Basic AI Q&A</li>
                  <li>Access to meal timeline</li>
                  <li>Standard support</li>
                  <li>Basic analytics</li>
                  <li>Community access</li>
                </ul>
                <div className="pricing-price">Free</div>
                <button className="pricing-btn" onClick={() => navigate('/signup')}>Start Free</button>
              </div>
              <div className="pricing-card premium best-value">
                <h3 style={{ color: '#1a237e' }}><span role="img" aria-label="premium">👑</span> Premium</h3>
                <ul style={{ fontSize: '1.15rem' }}>
                  <li>All Normal features</li>
                  <li>Advanced AI assistant</li>
                  <li>Priority support</li>
                  <li>Alternative food suggestions</li>
                  <li>Upload medical reports</li>
                  <li>Unlimited recommendations</li>
                  <li>Personal dietitian Q&A</li>
                  <li>Early access to new features</li>
                </ul>
                <div className="pricing-price">₹199/mo <span style={{ color: '#64748b', fontSize: '0.95rem' }}>(or $2.49/mo)</span></div>
                <button className="pricing-btn premium">Go Premium</button>
              </div>
            </div>
          </section>
        </div>
        <footer className="landing-footer">
          &copy; {new Date().getFullYear()} Medimeal. All rights reserved.
        </footer>
      </div>
    </>
  );
};

export default Landing;